// data.js
export const foodItems = [
  {
    name: "Home made pizza",
    price: "₹160",
    image: "images/JTGeats/food_item1.png",
    rating: 4.7,
    deliveryTime: "50-55 min",
    offer: "50%",
  },
  {
    name: "Cheesy pizza",
    price: "₹190",
    image: "images/JTGeats/food_item2.png",
    rating: 4.1,
    deliveryTime: "60-65 min",
    offer: "",
  },
  {
    name: "Tomato pizza",
    price: "₹180",
    image: "images/JTGeats/food_item3.png",
    rating: 4.4,
    deliveryTime: "50-55 min",
    offer: "20%",
  },
  {
    name: "Farm House pizza",
    price: "₹260",
    image: "images/JTGeats/food_item4.png",
    rating: 4.9,
    deliveryTime: "50-55 min",
    offer: "",
  },
  {
    name: "Regular pizza",
    price: "₹140",
    image: "images/JTGeats/food_item5.png",
    rating: 3.7,
    deliveryTime: "30-35 min",
    offer: "50%",
  },
  {
    name: "Special pizza",
    price: "₹360",
    image: "images/JTGeats/food_item6.png",
    rating: 4.9,
    deliveryTime: "40-50 min",
    offer: "",
  },
  {
    name: "Pizza Combo",
    price: "₹400",
    image: "images/JTGeats/food_item7.png",
    rating: 4.8,
    deliveryTime: "50-55 min",
    offer: "20%",
  },
  {
    name: "Tandoori pizza",
    price: "₹160",
    image: "images/JTGeats/food_item8.png",
    rating: 4.5,
    deliveryTime: "40-45 min",
    offer: "50%",
  },
  {
    name: "Home made pizza",
    price: "₹160",
    image: "images/JTGeats/food_item1.png",
    rating: 4.7,
    deliveryTime: "50-55 min",
    offer: "50%",
  },
  {
    name: "Cheesy pizza",
    price: "₹190",
    image: "images/JTGeats/food_item2.png",
    rating: 4.1,
    deliveryTime: "60-65 min",
    offer: "",
  },
  {
    name: "Tomato pizza",
    price: "₹180",
    image: "images/JTGeats/food_item3.png",
    rating: 4.4,
    deliveryTime: "50-55 min",
    offer: "",
  },
  {
    name: "Farm House pizza",
    price: "₹260",
    image: "images/JTGeats/food_item4.png",
    rating: 4.9,
    deliveryTime: "50-55 min",
    offer: "20%",
  },
  // Add more food items as needed
]
